### ISSUE TITLE
Readtimeout when periods exceed 30 days

### ISSUE THREAD

**Issue by ZroMnc** [zalando-stups/fullstop-cli#16]
When listing violations you get this:

``` bash


Traceback (most recent call last):
  File "/usr/local/bin/fullstop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/fullstop/cli.py", line 259, in main
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fullstop/cli.py", line 187, in list_violations
    r = request(url, '/api/violations', token, params=params)
  File "/usr/local/lib/python3.5/dist-packages/fullstop/api.py", line 13, in request
    params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='<url>', port=443): Read timed out. (read timeout=10)
```

**Comment by hjacobs** [comment]
Somebody already reported this (in the wrong repo): https://github.com/zalando-stups/fullstop/issues/447
